# Flickering Test Configuration
# This configuration creates multiple processes that generate logs at different rates
# to help reproduce and test the flickering issue in the LogPreview component

[[process]]
name = "fast-logger"
command = "./fast-logger.sh"

[[process]]
name = "medium-logger"
command = "./medium-logger.sh"

[[process]]
name = "slow-logger"
command = "./slow-logger.sh"

[[process]]
name = "burst-logger"
command = "./burst-logger.sh"

# Add a simple static process for comparison
[[process]]
name = "static-process"
command = "echo 'Static process started' && sleep infinity"