[[process]]
name = "buy-groceries"
command = "echo 'buying groceries' && sleep 3"

[[process]]
name = "cook-dinner"
command = "echo 'im cooking dinner' && sleep 5"
deps = ["buy-groceries"]

[[process]]
name = "eat-dinner"
command = "echo 'eating dinner' && sleep 3"
deps = ["cook-dinner"]

