version = 0

[[process]]
name = "buy-groceries"
command = "echo 'buying groceries' && sleep 3"

[[process]]
name = "cook-dinner"
command = "echo 'im cooking dinner' && sleep 5"
deps = [{ name = "buy-groceries", condition = "succeeded" }]

[[process]]
name = "eat-dinner"
command = "echo 'eating dinner' && sleep 3"
deps = [{ name = "cook-dinner", condition = "succeeded" }]

