name = "example configuration"

[[process]]
name = "hello process"
command = "echo hello"

[[process]]
name = "world process"
command = "echo world"

[[process]]
name = "deez process"
command = "echo deez"

[[process]]
name = "nutz process"
command = "echo nutz"

[[process]]
name = "dummy timer process"
command = "for i in {1..30}; do echo \"Message $i from dummy process\"; sleep 2; done"
